language: groovy
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
 - ./gradlew createTestDb check coveralls

before_install:
  - chmod +x ./gradlew
  - ./gradlew --no-daemon startDb

install:
  - ./gradlew --no-daemon createDb

script:
  - ./gradlew --no-daemon assemble

script:
  - ./gradlew --no-daemon check
